GerenciadorLives/Models/Inscritos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace GerenciadorLives.Models
{
    public partial class Inscritos
    {
        public Inscritos()
        {
            Inscricoes = new HashSet<Inscricoes>();
        }

        public int InscritoId { get; set; }
        public string Nome { get; set; }
        [DataType(DataType.EmailAddress)] 
        public string Email { get; set; }
        public string Instagram { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        [Display(Name = "Data de Nascimento")] 
        public DateTime DataNascimento { get; set; }

        public virtual ICollection<Inscricoes> Inscricoes { get; set; }
    }
}

GerenciadorLives/Controllers/InscricoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorLives.Models;

namespace GerenciadorLives.Controllers
{
    public class InscricoesController : Controller
    {
        private readonly AppDbContext _context;

        public InscricoesController(AppDbContext context)
        {
            _context = context;
        }


        // GET: Inscricoes
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Inscricoes.Include(i => i.Inscrito).Include(i => i.Live);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Inscricoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscricoes = await _context.Inscricoes
                .Include(i => i.Inscrito)
                .Include(i => i.Live)
                .FirstOrDefaultAsync(m => m.InscricaoId == id);
            if (inscricoes == null)
            {
                return NotFound();
            }
            return View(inscricoes);
        }

        // GET: Inscricoes/Create
        public IActionResult Create()
        {



            ViewData["InscritoId"] = new SelectList(_context.Inscritos, "InscritoId", "Nome");
            ViewData["LiveId"] = new SelectList(_context.Lives, "LiveId", "Nome");
            return View();
        }

        // POST: Inscricoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LiveId,InscritoId")] Inscricoes inscricoes)
        {

            if (ModelState.IsValid)
            {
                var lives = await _context.Lives.FindAsync(inscricoes.LiveId);
                inscricoes.ValorInscricao = lives.Valor;
                inscricoes.DataVencimento = lives.Data.AddDays(-2);
                _context.Add(inscricoes);
                await _context.SaveChangesAsync();        
                return RedirectToAction("Edit", new { ID = inscricoes.InscricaoId });               

            }
            ViewData["InscritoId"] = new SelectList(_context.Inscritos, "InscritoId", "Nome", inscricoes.InscritoId);
            ViewData["LiveId"] = new SelectList(_context.Lives, "LiveId", "Nome", inscricoes.LiveId);
            return View(inscricoes);
        }

        // GET: Inscricoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscricoes = await _context.Inscricoes
            .Include(i => i.Inscrito)
            .Include(i => i.Live)
            .FirstOrDefaultAsync(m => m.InscricaoId == id);

            if (inscricoes == null)
            {
                return NotFound();
            }
            return View(inscricoes);
        }

        // POST: Inscricoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.    

        
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditIn(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }          

            var inscricoes = await _context.Inscricoes
            .Include(i => i.Inscrito)
            .Include(i => i.Live)
            .FirstOrDefaultAsync(m => m.InscricaoId == id);

            if (await TryUpdateModelAsync<Inscricoes>(inscricoes,
                "",
                i => i.StatusPagamento))
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {                    
                    ModelState.AddModelError("", "Não foi possivel concluir a operação. " +
                        "tente novamente.");
                }
                return RedirectToAction(nameof(Index));
            }            
            return View(inscricoes);
        }

        // GET: Inscricoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscricoes = await _context.Inscricoes
                .Include(i => i.Inscrito)
                .Include(i => i.Live)
                .FirstOrDefaultAsync(m => m.InscricaoId == id);
            if (inscricoes == null)
            {
                return NotFound();
            }

            return View(inscricoes);
        }

        // POST: Inscricoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inscricoes = await _context.Inscricoes.FindAsync(id);
            _context.Inscricoes.Remove(inscricoes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InscricoesExists(int id)
        {
            return _context.Inscricoes.Any(e => e.InscricaoId == id);
        }
    }
}

GerenciadorLives/Controllers/InscritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorLives.Models;

namespace GerenciadorLives.Controllers
{
    public class InscritosController : Controller
    {
        private readonly AppDbContext _context;

        public InscritosController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Inscritos
        public async Task<IActionResult> Index(string filtro)
        {
            ViewData["FiltroAtual"] = filtro;
            var inscritos = from i in _context.Inscritos
                              select i;

            if (!String.IsNullOrEmpty(filtro))
            {
                inscritos = inscritos.Where(i => i.Nome.Contains(filtro)
                                       || i.Email.Contains(filtro)
                                       || i.Instagram.Contains(filtro)
                                       );
            }
            return View(await inscritos.AsNoTracking().ToListAsync());
        }

        // GET: Inscritos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscritos = await _context.Inscritos
                .Include(i => i.Inscricoes)
                    .ThenInclude(i => i.Live)
                    .FirstOrDefaultAsync(m => m.InscritoId == id);

            if (inscritos == null)
            {
                return NotFound();
            }

            return View(inscritos);
        }

        // GET: Inscritos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Inscritos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InscritoId,Nome,Email,Instagram,DataNascimento")] Inscritos inscritos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inscritos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(inscritos);
        }

        // GET: Inscritos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscritos = await _context.Inscritos.FindAsync(id);
            if (inscritos == null)
            {
                return NotFound();
            }
            return View(inscritos);
        }

        // POST: Inscritos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InscritoId,Nome,Email,Instagram,DataNascimento")] Inscritos inscritos)
        {
            if (id != inscritos.InscritoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inscritos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InscritosExists(inscritos.InscritoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(inscritos);
        }

        // GET: Inscritos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inscritos = await _context.Inscritos
                .FirstOrDefaultAsync(m => m.InscritoId == id);
            if (inscritos == null)
            {
                return NotFound();
            }

            return View(inscritos);
        }

        // POST: Inscritos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inscritos = await _context.Inscritos.FindAsync(id);
            _context.Inscritos.Remove(inscritos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InscritosExists(int id)
        {
            return _context.Inscritos.Any(e => e.InscritoId == id);
        }
    }
}

GerenciadorLives/Views/Inscritos/Create.cshtml
@model GerenciadorLives.Models.Inscritos

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Novo Inscrito</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instagram" class="control-label"></label>
                <input asp-for="Instagram" class="form-control" />
                <span asp-validation-for="Instagram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorLives/Views/Inscritos/Delete.cshtml
@model GerenciadorLives.Models.Inscritos

@{
    ViewData["Title"] = "Excluir";
}
<h1>Excluir Inscrito</h1>

<h3>Tem certeza que deseja excluir o registro?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instagram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instagram)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InscritoId" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Listar</a>
    </form>
</div>

GerenciadorLives/Views/Inscritos/Details.cshtml
@model GerenciadorLives.Models.Inscritos

@{
    ViewData["Title"] = "Details";
}
<h1>Detalhes do Inscrito</h1>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Instagram)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Instagram)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Inscricoes)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Lives</th>
                    <th>Data</th>
                    <th>Status Pagamento</th>
                    <th></th>
                </tr>
                @foreach (var item in Model.Inscricoes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Live.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Live.Data)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StatusPagamento)
                        </td>
                        <td>
                            <a asp-action="Details" asp-controller="Inscricoes" asp-route-id="@item.InscricaoId">Detalhe</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.InscritoId">Alterar</a> |
    <a asp-action="Index">Listar</a>
</div>

GerenciadorLives/Views/Inscritos/Edit.cshtml
@model GerenciadorLives.Models.Inscritos

@{
    ViewData["Title"] = "Alterar";
}
<h1>Alterar Inscrito</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InscritoId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instagram" class="control-label"></label>
                <input asp-for="Instagram" class="form-control" />
                <span asp-validation-for="Instagram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorLives/Views/Inscritos/Index.cshtml
@model IEnumerable<GerenciadorLives.Models.Inscritos>

@{
    ViewData["Title"] = "Inscritos";
}

<h1>Inscritos</h1>
<p>
    <a asp-action="Create">Cadastrar Inscrito</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            <input type="text" name="filtro" value="@ViewData["FiltroAtual"]" />
            <input type="submit" value="Buscar" class="btn btn-primary" /> |
            <a asp-action="Index">Lista Completa</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instagram)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instagram)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.InscritoId">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.InscritoId">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.InscritoId">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>