GerenciadorLives/Models/Instrutores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace GerenciadorLives.Models
{
    public partial class Instrutores
    {
        public Instrutores()
        {
            Lives = new HashSet<Lives>();
        }

        public int InstrutorId { get; set; }
        public string Nome { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Instagram { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        [Display(Name = "Data de Nascimento")]
        public DateTime DataNascimento { get; set; }

        public virtual ICollection<Lives> Lives { get; set; }
    }
}

GerenciadorLives/Controllers/InstrutoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorLives.Models;

namespace GerenciadorLives.Controllers
{
    public class InstrutoresController : Controller
    {
        private readonly AppDbContext _context;

        public InstrutoresController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Instrutores
        public async Task<IActionResult> Index(string filtro)
        {

            ViewData["FiltroAtual"] = filtro;
            var instrutores = from i in _context.Instrutores
                              select i;

            if (!String.IsNullOrEmpty(filtro))
            {
                instrutores = instrutores.Where(i => i.Nome.Contains(filtro)
                                       || i.Email.Contains(filtro)
                                       || i.Instagram.Contains(filtro)
                                       );
            }
            return View(await instrutores.AsNoTracking().ToListAsync());            
        }

        // GET: Instrutores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instrutores = await _context.Instrutores
                 .Include(i => i.Lives)         
                 .AsNoTracking()
                .FirstOrDefaultAsync(i => i.InstrutorId == id);

            if (instrutores == null)
            {
                return NotFound();
            }

            return View(instrutores);
        }

        // GET: Instrutores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Instrutores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstrutorId,Nome,Email,Instagram,DataNascimento")] Instrutores instrutores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instrutores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(instrutores);
        }

        // GET: Instrutores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instrutores = await _context.Instrutores.FindAsync(id);
            if (instrutores == null)
            {
                return NotFound();
            }
            return View(instrutores);
        }

        // POST: Instrutores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstrutorId,Nome,Email,Instagram,DataNascimento")] Instrutores instrutores)
        {
            if (id != instrutores.InstrutorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instrutores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstrutoresExists(instrutores.InstrutorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(instrutores);
        }

        // GET: Instrutores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instrutores = await _context.Instrutores
                .FirstOrDefaultAsync(m => m.InstrutorId == id);
            if (instrutores == null)
            {
                return NotFound();
            }

            return View(instrutores);
        }

        // POST: Instrutores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instrutores = await _context.Instrutores.FindAsync(id);
            _context.Instrutores.Remove(instrutores);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstrutoresExists(int id)
        {
            return _context.Instrutores.Any(e => e.InstrutorId == id);
        }
    }
}

GerenciadorLives/Controllers/LivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorLives.Models;

namespace GerenciadorLives.Controllers
{
    public class LivesController : Controller
    {
        private readonly AppDbContext _context;

        public LivesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Lives
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Lives.Include(l => l.Instrutor);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Lives/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lives = await _context.Lives
                .Include(l => l.Instrutor)
                .FirstOrDefaultAsync(m => m.LiveId == id);
            if (lives == null)
            {
                return NotFound();
            }

            return View(lives);
        }

        // GET: Lives/Create
        public IActionResult Create()
        {
            ViewData["InstrutorId"] = new SelectList(_context.Instrutores, "InstrutorId", "Nome");
            return View();
        }

        // POST: Lives/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LiveId,Nome,Descricao,InstrutorId,Data,Duracao,Valor")] Lives lives)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lives);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstrutorId"] = new SelectList(_context.Instrutores, "InstrutorId", "Nome", lives.InstrutorId);
            return View(lives);
        }

        // GET: Lives/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lives = await _context.Lives.FindAsync(id);
            if (lives == null)
            {
                return NotFound();
            }
            ViewData["InstrutorId"] = new SelectList(_context.Instrutores, "InstrutorId", "Nome", lives.InstrutorId);
            return View(lives);
        }

        // POST: Lives/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LiveId,Nome,Descricao,InstrutorId,Data,Duracao,Valor")] Lives lives)
        {
            if (id != lives.LiveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lives);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivesExists(lives.LiveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstrutorId"] = new SelectList(_context.Instrutores, "InstrutorId", "Nome", lives.InstrutorId);
            return View(lives);
        }

        // GET: Lives/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lives = await _context.Lives
                .Include(l => l.Instrutor)
                .FirstOrDefaultAsync(m => m.LiveId == id);
            if (lives == null)
            {
                return NotFound();
            }

            return View(lives);
        }

        // POST: Lives/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lives = await _context.Lives.FindAsync(id);
            _context.Lives.Remove(lives);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivesExists(int id)
        {
            return _context.Lives.Any(e => e.LiveId == id);
        }
    }
}

GerenciadorLives/Views/Instrutores/Create.cshtml
@model GerenciadorLives.Models.Instrutores

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Novo Instrutor</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instagram" class="control-label"></label>
                <input asp-for="Instagram" class="form-control" />
                <span asp-validation-for="Instagram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorLives/Views/Instrutores/Delete.cshtml
@model GerenciadorLives.Models.Instrutores

@{
    ViewData["Title"] = "Excluir";
}
<h1>Excluir Instrutor</h1>

<h3>Tem certeza que deseja excluir o registro?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instagram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instagram)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InstrutorId" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Listar</a>
    </form>
</div>

GerenciadorLives/Views/Instrutores/Details.cshtml
@model GerenciadorLives.Models.Instrutores

@{
    ViewData["Title"] = "Detalhe";
}

<h1>Detalhe</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Instagram)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Instagram)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Lives)
        </dt>



        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Lives</th>
                    <th>Data</th>
                    <th></th>
                </tr>
                @foreach (var item in Model.Lives)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
                <td>                    
                    <a asp-action="Details" asp-controller="Lives" asp-route-id="@item.LiveId">Detalhe</a>
                </td>
            </tr>
                }
            </table>
        </dd>


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.InstrutorId">Alterar</a> |
    <a asp-action="Index">Listar</a>
</div>

GerenciadorLives/Views/Instrutores/Edit.cshtml
@model GerenciadorLives.Models.Instrutores

@{
    ViewData["Title"] = "Alterar";
}
<h1>Alterar Instrutor</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InstrutorId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instagram" class="control-label"></label>
                <input asp-for="Instagram" class="form-control" />
                <span asp-validation-for="Instagram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorLives/Views/Instrutores/Index.cshtml
@model IEnumerable<GerenciadorLives.Models.Instrutores>

@{
    ViewData["Title"] = "Instrutores";
}

<h1>Instrutores</h1>

<p>
    <a asp-action="Create">Cadastrar</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            <input type="text" name="filtro" value="@ViewData["FiltroAtual"]" />
            <input type="submit" value="Buscar" class="btn btn-primary" /> |
            <a asp-action="Index">Lista Completa</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instagram)
            </th>            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instagram)
            </td>            
            <td>
                <a asp-action="Edit" asp-route-id="@item.InstrutorId">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.InstrutorId">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.InstrutorId">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>